[project]
name = 'crispy_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.node_registry]
path = 'contracts/node_registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_price_oracle_update]
path = 'contracts/storage_with_price_oracle_update.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
